"""Initial migration

Revision ID: 79916ebc5cb9
Revises: 
Create Date: 2025-02-03 21:36:38.592347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79916ebc5cb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.NUMERIC(), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('task_description', sa.TEXT(), nullable=False),
    sa.Column('assignee', sa.VARCHAR(length=50), nullable=False),
    sa.Column('assignor', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('task_deadline', sa.DATE(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('task_id'),
    sa.UniqueConstraint('task_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
